# Generated by Django 5.1.3 on 2025-09-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='mentormatchstudent',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='mentorforstudent',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='mentorforscholier',
            name='study',
        ),
        migrations.RemoveField(
            model_name='mentorforscholier',
            name='university',
        ),
        migrations.RemoveField(
            model_name='mentorforscholier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentorforstudent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentormatchscholier',
            name='study',
        ),
        migrations.RemoveField(
            model_name='mentormatchscholier',
            name='university',
        ),
        migrations.RemoveField(
            model_name='mentormatchscholier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentormatchstudent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='room',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='study',
            name='university',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
        migrations.DeleteModel(
            name='MentorForScholier',
        ),
        migrations.DeleteModel(
            name='MentorForStudent',
        ),
        migrations.DeleteModel(
            name='MentorMatchScholier',
        ),
        migrations.DeleteModel(
            name='MentorMatchStudent',
        ),
        migrations.DeleteModel(
            name='MessageRoom',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
