# Generated by Django 5.1.3 on 2025-09-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advokate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advokaterequest',
            name='email',
            field=models.EmailField(blank=True, default='None', max_length=254),
        ),
        migrations.AlterField(
            model_name='advokaterequest',
            name='phone_number',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
