# Generated by Django 5.1.3 on 2025-09-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advokate', '0002_alter_advokaterequest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advokaterequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='advokaterequest',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
