# Generated by Django 5.1.3 on 2025-10-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prof_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('L', 'LAWYER'), ('B', 'DUO_BOOKIE'), ('A', 'ADMIN'), ('U', 'COMMON_USER'), ('P', 'PARTNER')], default='U', max_length=1, verbose_name='User Type'),
        ),
    ]
